/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-tertiary': '#ffffff',
        'on-surface': '#0b1c30',
        tertiary: '#00442d',
        'on-primary': '#ffffff',
        'on-secondary-fixed': '#131b2e',
        'on-primary-fixed-variant': '#372abf',
        'on-surface-variant': '#464554',
        'on-tertiary-fixed': '#002114',
        'secondary-fixed-dim': '#bec6e0',
        'on-tertiary-container': '#66daa8',
        primary: '#2a14b4',
        'on-background': '#0b1c30',
        'on-secondary': '#ffffff',
        'on-secondary-fixed-variant': '#3f465c',
        'tertiary-fixed': '#85f8c4',
        'secondary-fixed': '#dae2fd',
        'surface-container-lowest': '#ffffff',
        'surface-variant': '#d3e4fe',
        'on-tertiary-fixed-variant': '#005137',
        'surface-tint': '#5148d7',
        'outline-variant': '#c7c4d7',
        background: '#f8f9ff',
        outline: '#777586',
        'inverse-on-surface': '#eaf1ff',
        'surface-bright': '#f8f9ff',
        'on-primary-fixed': '#100069',
        'surface-container-high': '#dce9ff',
        'error-container': '#ffdad6',
        'inverse-primary': '#c3c0ff',
        'surface-container': '#e5eeff',
        'tertiary-container': '#005e40',
        'primary-container': '#4338ca',
        'surface-container-low': '#eff4ff',
        'on-primary-container': '#c1beff',
        'secondary-container': '#dae2fd',
        'inverse-surface': '#213145',
        'tertiary-fixed-dim': '#68dba9',
        secondary: '#565e74',
        'on-secondary-container': '#5c647a',
        surface: '#f8f9ff',
        'on-error': '#ffffff',
        error: '#ba1a1a',
        'surface-dim': '#cbdbf5',
        'surface-container-highest': '#d3e4fe',
        'on-error-container': '#93000a',
        'primary-fixed-dim': '#c3c0ff',
        'primary-fixed': '#e3dfff',
      },
      fontFamily: {
        'body-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-xl': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'data-mono': ['JetBrains Mono', 'monospace'],
        'headline-xl-mobile': ['Plus Jakarta Sans', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'title-md': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-xl': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-sm': ['18px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'data-mono': ['13px', { lineHeight: '18px', fontWeight: '500' }],
        'headline-xl-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.01em', fontWeight: '500' }],
        'title-md': ['16px', { lineHeight: '22px', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
